# -*- coding: utf-8 -*-
"""HandDrawingModel1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suDfljD0l4jfLX2JXMJTUR6Haz-vmhUD
"""

!pip install git+https://github.com/PyTorchLightning/pytorch-lightning

# Commented out IPython magic to ensure Python compatibility.
import os
import cv2
import random
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import random_split
from torch.utils.data import DataLoader, Dataset, Subset
from torch.utils.data import random_split, SubsetRandomSampler
from torchvision import datasets, transforms, models 
from torchvision.datasets import ImageFolder
from torchvision.transforms import ToTensor
from torchvision.utils import make_grid
from pytorch_lightning import LightningModule
from pytorch_lightning import Trainer
import pytorch_lightning as pl
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from PIL import Image

transform=transforms.Compose([
        transforms.RandomRotation(10),      # rotate +/- 10 degrees
        transforms.RandomHorizontalFlip(),  # reverse 50% of images
        transforms.Resize(224),             # resize shortest side to 224 pixels
        transforms.CenterCrop(224),         # crop longest side to 224 pixels at center
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
])

trainset=datasets.ImageFolder(root="/content/drive/MyDrive/Parkinson's Disease /handDrawing/spiral/training",transform=None)
testset=datasets.ImageFolder(root="/content/drive/MyDrive/Parkinson's Disease /handDrawing/spiral/testing",transform=None)

class_names=trainset.classes

class DataModule(pl.LightningDataModule):
    
    def __init__(self, transform=transform, batch_size=32):
        super().__init__()
        self.train_dir = "/content/drive/MyDrive/Parkinson's Disease /handDrawing/spiral/training"
        self.test_dir = "/content/drive/MyDrive/Parkinson's Disease /handDrawing/spiral/testing"
        self.transform = transform
        self.batch_size = batch_size

    def setup(self, stage=None):
        if stage == 'fit' or stage is None:
            self.trainset = datasets.ImageFolder(root=self.train_dir, transform=self.transform)
            self.train_dataloader_ = DataLoader(self.trainset, batch_size=self.batch_size, shuffle=True)

        if stage == 'test' or stage is None:
            self.testset = datasets.ImageFolder(root=self.test_dir, transform=self.transform)
            self.test_dataloader_ = DataLoader(self.testset, batch_size=self.batch_size)

    def train_dataloader(self):
        return self.train_dataloader_

    def test_dataloader(self):
        return self.test_dataloader_

class ConvolutionalNetwork(LightningModule):
    
    def __init__(self):
        super(ConvolutionalNetwork, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 3, 1)
        self.conv2 = nn.Conv2d(6, 16, 3, 1)
        self.fc1 = nn.Linear(16 * 54 * 54, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 20)
        self.fc4 = nn.Linear(20, len(class_names))

    def forward(self, X):
        X = F.relu(self.conv1(X))
        X = F.max_pool2d(X, 2, 2)
        X = F.relu(self.conv2(X))
        X = F.max_pool2d(X, 2, 2)
        X = X.view(-1, 16 * 54 * 54)
        X = F.relu(self.fc1(X))
        X = F.relu(self.fc2(X))
        X = F.relu(self.fc3(X))
        X = self.fc4(X)
        return F.log_softmax(X, dim=1)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=0.001)
        return optimizer

    def training_step(self, train_batch, batch_idx):
        X, y = train_batch
        y_hat = self(X)
        loss = F.cross_entropy(y_hat, y)
        pred = y_hat.argmax(dim=1, keepdim=True)
        acc = pred.eq(y.view_as(pred)).sum().item() / y.shape[0]
        self.log("train_loss", loss)
        self.log("train_acc", acc)
        return loss

    def validation_step(self, val_batch, batch_idx):
        X, y = val_batch
        y_hat = self(X)
        loss = F.cross_entropy(y_hat, y)
        pred = y_hat.argmax(dim=1, keepdim=True)
        acc = pred.eq(y.view_as(pred)).sum().item() / y.shape[0]
        self.log("val_loss", loss)
        self.log("val_acc", acc)

    def test_step(self, test_batch, batch_idx):
        X, y = test_batch
        y_hat = self(X)
        loss = F.cross_entropy(y_hat, y)
        pred = y_hat.argmax(dim=1, keepdim=True)
        acc = pred.eq(y.view_as(pred)).sum().item() / y.shape[0]
        self.log("test_loss", loss)
        self.log("test_acc", acc)

if __name__ == '__main__':
    datamodule = DataModule()
    datamodule.setup(stage='fit')
    model = ConvolutionalNetwork()
    trainer = pl.Trainer(max_epochs=600)
    trainer.fit(model, datamodule)
    datamodule.setup(stage='test')
    test_loader = datamodule.test_dataloader()
    trainer.test(dataloaders=test_loader)

for images, labels in datamodule.train_dataloader():
    break
im=make_grid(images,nrow=16)

plt.figure(figsize=(12,12))
plt.imshow(np.transpose(im.numpy(),(1,2,0)))

inv_normalize=transforms.Normalize(mean=[-0.485/0.229,-0.456/0.224,-0.406/0.225],
                                   std=[1/0.229,1/0.224,1/0.225])
im=inv_normalize(im)

plt.figure(figsize=(12,12))
plt.imshow(np.transpose(im.numpy(),(1,2,0)))

torch.save(model.state_dict(), 'parkinsons_spiral_model.pkl')

model = ConvolutionalNetwork()
model.load_state_dict(torch.load('parkinsons_spiral_model.pkl'))

new_image = Image.open("/content/V03PE04.png")
preprocessed_image = transform(new_image)

new_image_tensor = torch.Tensor(preprocessed_image)
prediction = model(new_image_tensor.unsqueeze(0))

prediction

softmax = torch.nn.Softmax(dim=1)
probabilities = softmax(prediction)

probabilities

predicted_class_index = torch.argmax(probabilities, dim=1)

predicted_class_index

predicted_class_label = class_names[predicted_class_index]

predicted_class_label

len(class_names)